# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SuperParaSettingDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SuperParaSettingDialog(object):
    def setupUi(self, SuperParaSettingDialog):
        SuperParaSettingDialog.setObjectName("SuperParaSettingDialog")
        SuperParaSettingDialog.resize(400, 300)
        self.ConfirmBtn = QtWidgets.QDialogButtonBox(SuperParaSettingDialog)
        self.ConfirmBtn.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.ConfirmBtn.setOrientation(QtCore.Qt.Horizontal)
        self.ConfirmBtn.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.ConfirmBtn.setObjectName("ConfirmBtn")
        self.widget = QtWidgets.QWidget(SuperParaSettingDialog)
        self.widget.setGeometry(QtCore.QRect(70, 40, 217, 47))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.machine_num_input = QtWidgets.QLineEdit(self.widget)
        self.machine_num_input.setObjectName("machine_num_input")
        self.horizontalLayout.addWidget(self.machine_num_input)
        self.horizontalLayout.setStretch(0, 3)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout.setStretch(2, 5)

        self.retranslateUi(SuperParaSettingDialog)
        self.ConfirmBtn.accepted.connect(SuperParaSettingDialog.accept)
        self.ConfirmBtn.rejected.connect(SuperParaSettingDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(SuperParaSettingDialog)

    def retranslateUi(self, SuperParaSettingDialog):
        _translate = QtCore.QCoreApplication.translate
        SuperParaSettingDialog.setWindowTitle(_translate("SuperParaSettingDialog", "Dialog"))
        self.label.setText(_translate("SuperParaSettingDialog", "机器数"))
